import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >      
        <div className="min-h-screen text-white bg-linear-to-t from-(--maincolor) to-(--bgcolor) py-[5vh] md:py-[10vh]">
          <div className='bg-linear-to-l text-(--text) from-(--bgfcolor) to-(--bgcolor) mx-auto min-h-[80vh] w-[95vw] rounded-4xl drope'><Navbar />
            {children} <Footer /></div></div>

      </body>
    </html>
  );
}
